# Generated by Django 5.2.2 on 2025-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
